apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pos-mk1

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/app.yaml
  - ../../base/ingress.yaml
  - secret.aws.yaml

patches:
  - path: configmap.aws.patch.yaml
  - path: ingress.aws.patch.yaml

images:
  - name: personal-operating-system-mk1-app
    newName: 948360715051.dkr.ecr.ap-northeast-2.amazonaws.com/personal-operating-system-mk1-app
    newTag: latest
